#!/bin/bash

URL=https://github.com/msaf1980/carbon-c-relay.git
BRANCH=master
unset COMMIT

RPMBUILDDIR=${HOME}/rpmbuild
SOURCEDIR=${RPMBUILDDIR}/SOURCES
BUILDIR=${RPMBUILDDIR}/SOURCES

git_clone() {
    git clone -b "${BRANCH}" --single-branch "${URL}" -o "${NAME}" || return 1
    cd "${NAME}" || return 1
    return 0
}

git_pull_branch() {
    cd "${NAME}" || return 1
    git checkout "${BRANCH}" || return 1
    git pull --force || return 1
    return 0
}

git_version() {
    unset VERSION
    unset RELEASE
    GIT_VERSION="$(git describe --always --tags)" && {
        set -f; IFS='-' ; set -- ${GIT_VERSION}
        VERSION=$1; [ -z "$3" ] && RELEASE=$2 || RELEASE=$2.$3
        set +f; unset IFS

        [ "$RELEASE" == "" -a "$VERSION" != "" ] && RELEASE=0 

        if echo $VERSION | egrep '^v[0-9]+\.[0-9]+$' >/dev/null; then
            VERSION=${VERSION:1:${#VERSION}}
        else
            echo "failed to extract version from ${GIT_VERSION}" >&2
            return 1
        fi
        return 0
    }
    return 1
}

git_commit() {
    if [ -n "${COMMIT}" ]; then
        git reset --hard "${SCN}" || return 1
    else
        COMMIT=$( git log -n 1 --pretty=format:'%H' )
        [ "$?" == "0" ] || return 1
    fi
    return 0
}

NAME=$( basename ${URL} | sed -e 's/\.git$//' )

[ -n "${NAME}" ] || {
    echo "can't extract name from url ${URL}" >&2
    exit 1
}
if [ -d "${NAME}" ]; then
    #git_pull_branch || exit 1
    rm -rf "${NAME}" || exit 1
else
    git_clone || exit 1
fi

git_commit || exit 1
git_version || exit 1

printf "Version %s  Release %s Commit %s\n" "$VERSION" "$RELEASE" "$COMMIT"
cd .. || exit 1
[ -d "${NAME}-${VERSION}.${RELEASE}" ] && {
    rm -rf "${NAME}-${VERSION}.${RELEASE}" || exit 1
}
rm -rf "${NAME}/.git"
mv "${NAME}" "${NAME}-${VERSION}.${RELEASE}" || exit 1

tar -cjf "${SOURCEDIR}/${NAME}-${VERSION}.${RELEASE}.tbz" "${NAME}-${VERSION}.${RELEASE}" || exit 1
cp -f SOURCES/* "${SOURCEDIR}/"  || exit 1

cd "${SOURCEDIR}" && {
  rpmbuild -ba "${SOURCEDIR}/${NAME}.spec" --define "vers ${VERSION}" --define "rel ${RELEASE}" --define "commit ${COMMIT}" && {
    exit 1
  } || {
    echo "Build failed !! Fix and run" >&2
    echo rpmbuild -ba \"${SOURCEDIR}/${NAME}.spec\" --define \"vers ${VERSION}\" --define \"rel ${RELEASE}\" --define \"commit ${COMMIT}\" >&2
  }
}
exit 1
